# Generated by Django 2.2.5 on 2019-10-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='zip_codes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agencyqueue',
            name='zip_codes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='zip_codes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='programqueue',
            name='zip_codes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
