# Generated by Django 2.2.5 on 2019-10-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='old_id',
            field=models.CharField(help_text='Old needhou i', max_length=255, null=True),
        ),
    ]
