# Generated by Django 2.2.5 on 2019-10-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191014_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='ada_accessible',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='assistance_with_forms',
            field=models.CharField(help_text='Assistance to fill out intake forms', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='response_requests',
            field=models.CharField(help_text='Response to Immigrations and Custom Enforcement requests', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='visual_aids',
            field=models.CharField(help_text='Visual aids for low-literacy clients', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='agencyqueue',
            name='ada_accessible',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='agencyqueue',
            name='assistance_with_forms',
            field=models.CharField(help_text='Assistance to fill out intake forms', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='agencyqueue',
            name='response_requests',
            field=models.CharField(help_text='Response to Immigrations and Custom Enforcement requests', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='agencyqueue',
            name='visual_aids',
            field=models.CharField(help_text='Visual aids for low-literacy clients', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='appointment_required',
            field=models.CharField(help_text='Appointment required?', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='case_management_provided',
            field=models.CharField(help_text='Is case management provided?', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='client_consult',
            field=models.CharField(help_text='Client consult before completing paperwork', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='disaster_recovery',
            field=models.CharField(help_text='Disaster recovery?', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='service_same_day_intake',
            field=models.CharField(help_text='Are services available same day as intake??', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='programqueue',
            name='appointment_required',
            field=models.CharField(help_text='Appointment required?', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='programqueue',
            name='case_management_provided',
            field=models.CharField(help_text='Is case management provided?', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='programqueue',
            name='client_consult',
            field=models.CharField(help_text='Client consult before completing paperwork', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='programqueue',
            name='disaster_recovery',
            field=models.CharField(help_text='Disaster recovery?', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='programqueue',
            name='service_same_day_intake',
            field=models.CharField(help_text='Are services available same day as intake??', max_length=5, null=True),
        ),
    ]
