# Generated by Django 2.2.5 on 2019-10-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agency_old_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencyqueue',
            old_name='verified',
            new_name='hilsc_verified',
        ),
        migrations.AddField(
            model_name='agency',
            name='hilsc_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
