# Generated by Django 2.2.5 on 2019-10-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191014_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
