# Generated by Django 2.2.5 on 2019-10-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191005_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='normalized_name',
        ),
        migrations.RemoveField(
            model_name='agencyqueue',
            name='normalized_name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='normalized_name',
        ),
        migrations.RemoveField(
            model_name='programqueue',
            name='normalized_name',
        ),
    ]
