# Generated by Django 2.2.5 on 2019-10-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_language_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['display_order'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.RenameField(
            model_name='language',
            old_name='order',
            new_name='display_order',
        ),
    ]
