# Generated by Django 2.2.5 on 2019-10-18 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191017_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
