# Generated by Django 2.2.5 on 2019-10-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(max_length=255)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('physical_address', models.TextField()),
                ('ada', models.TextField()),
                ('application_process', models.TextField()),
                ('documents_required', models.TextField()),
                ('fee_structure', models.TextField()),
                ('coverage_area', models.TextField()),
                ('service_type', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('alternative_name', models.TextField()),
                ('website', models.TextField()),
                ('appointment_required', models.TextField()),
                ('accepting_clients', models.TextField()),
                ('transportation', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('holiday_schedule', models.TextField()),
                ('service_area', models.TextField()),
                ('next_steps', models.TextField()),
                ('waitlist_wait', models.TextField()),
                ('other_program_enrollment', models.TextField()),
                ('other_eligibility', models.TextField()),
                ('id_accepted_notes', models.TextField()),
                ('proof_address', models.TextField()),
                ('appointment_required_notes', models.TextField()),
                ('service_available_intake', models.TextField()),
                ('service_available_intake_notes', models.TextField()),
                ('schedule_notes', models.TextField()),
                ('document_assistance', models.TextField()),
                ('visual_aids_offered', models.TextField()),
                ('consultation_opportunity', models.TextField()),
                ('enforcement_request_policy', models.TextField()),
                ('cultural_competency_offered', models.TextField()),
                ('zipcode_eligibility', models.TextField(blank=True, null=True)),
                ('age_eligibility', models.TextField(blank=True, null=True)),
                ('id_accepted_current', models.TextField(blank=True, null=True)),
                ('website_languages', models.TextField(blank=True, null=True)),
                ('frontline_languages', models.TextField(blank=True, null=True)),
                ('interpretation_offered', models.TextField(blank=True, null=True)),
                ('crisis_services_offered', models.TextField(blank=True, null=True)),
                ('document_languages', models.TextField(blank=True, null=True)),
                ('immigration_status', models.TextField(blank=True, null=True)),
                ('income_eligibility', models.TextField()),
                ('id_accepted_expired', models.TextField(blank=True, null=True)),
                ('gender_eligibility', models.TextField()),
                ('schedule', models.TextField(blank=True, null=True)),
                ('service_cost', models.TextField()),
                ('source', models.TextField()),
                ('a2s_verified', models.BooleanField(blank=True, null=True)),
                ('disaster_only', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'old_programs',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='program',
            name='incomes_percent_poverty_level',
            field=models.IntegerField(null=True),
        ),
    ]
