# Generated by Django 2.2.5 on 2019-10-27 20:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191026_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='geocode',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='geocode',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
