# Generated by Django 2.2.5 on 2019-11-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191027_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCodeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=2)),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('full_state', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'api_zip_codes',
                'ordering': ['zip_code', 'state', 'city'],
            },
        ),
    ]
