# Generated by Django 2.2.5 on 2019-11-09 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_zipcodedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programqueue',
            old_name='verified',
            new_name='immigration_accessibility_profile',
        ),
        migrations.AddField(
            model_name='program',
            name='immigration_accessibility_profile',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=350)),
                ('action', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_actionlog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_actions_logs',
            },
        ),
    ]
