# Generated by Django 2.2.5 on 2019-11-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191109_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='description',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='additional_info',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='info',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
