# Generated by Django 2.2.5 on 2019-11-09 13:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191109_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='additional_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=None, null=True, size=None),
        ),
    ]
