# Generated by Django 2.2.5 on 2019-11-09 13:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191109_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyqueue',
            name='geocode',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='programqueue',
            name='geocode',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='programqueue',
            name='incomes_percent_poverty_level',
            field=models.IntegerField(null=True),
        ),
    ]
