# Generated by Django 2.2.5 on 2019-11-16 19:33

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_auto_20191110_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_mode', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_app_settings',
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='emergency_mode',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='agencyqueue',
            name='emergency_mode',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='emergency_mode',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='programqueue',
            name='emergency_mode',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='old_id',
            field=models.CharField(help_text='Old needhou id', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProgramEmergencyQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=350)),
                ('description', models.TextField(null=True)),
                ('service_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None)),
                ('case_management_provided', models.CharField(help_text='Is case management provided?', max_length=5, null=True)),
                ('case_management_notes', models.TextField(null=True)),
                ('website', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('street', models.CharField(max_length=250, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('geocode', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('next_steps', models.TextField(null=True)),
                ('payment_service_cost', models.TextField(null=True)),
                ('payment_options', models.TextField(null=True)),
                ('age_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None)),
                ('zip_codes', models.CharField(max_length=500, null=True)),
                ('incomes_percent_poverty_level', models.IntegerField(null=True)),
                ('immigration_statuses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None)),
                ('requires_enrollment_in', models.TextField(null=True)),
                ('other_requirements', models.TextField(null=True)),
                ('documents_required', models.TextField(null=True)),
                ('appointment_required', models.CharField(help_text='Appointment required?', max_length=5, null=True)),
                ('appointment_notes', models.TextField(null=True)),
                ('schedule', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('walk_in_schedule', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('schedule_notes', models.TextField(null=True)),
                ('holiday_schedule', models.TextField(null=True)),
                ('service_same_day_intake', models.CharField(help_text='Are services available same day as intake??', max_length=5, null=True)),
                ('intake_notes', models.TextField(null=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=45), null=True, size=None)),
                ('crisis', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None)),
                ('disaster_recovery', models.CharField(help_text='Disaster recovery?', max_length=5, null=True)),
                ('transportation', models.TextField(null=True)),
                ('client_consult', models.CharField(help_text='Client consult before completing paperwork', max_length=5, null=True)),
                ('immigration_accessibility_profile', models.BooleanField(default=False, null=True)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_agency_programemergencyqueue', to='api.Agency')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_programemergencyqueue', to=settings.AUTH_USER_MODEL)),
                ('related_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_program_programemergencyqueue', to='api.Program')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_programemergencyqueue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_program_emergency_queue',
                'ordering': ['agency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgencyEmergencyQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=350)),
                ('website', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('street', models.CharField(max_length=250, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('geocode', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('next_steps', models.TextField(null=True)),
                ('payment_options', models.TextField(null=True)),
                ('age_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None)),
                ('zip_codes', models.CharField(max_length=500, null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('immigration_statuses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None)),
                ('accepted_ids_current', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None)),
                ('accepted_ids_expired', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None)),
                ('notes', models.TextField(null=True)),
                ('proof_of_address', models.CharField(max_length=250, null=True)),
                ('schedule', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('schedule_notes', models.TextField(null=True)),
                ('holiday_schedule', models.TextField(null=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=45), null=True, size=None)),
                ('documents_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=45), null=True, size=None)),
                ('website_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=45), null=True, size=None)),
                ('frontline_staff_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=45), null=True, size=None)),
                ('interpretations_available', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=45), null=True, size=None)),
                ('assistance_with_forms', models.CharField(help_text='Assistance to fill out intake forms', max_length=5, null=True)),
                ('visual_aids', models.CharField(help_text='Visual aids for low-literacy clients', max_length=5, null=True)),
                ('ada_accessible', models.CharField(max_length=5, null=True)),
                ('response_requests', models.CharField(help_text='Response to Immigrations and Custom Enforcement requests', max_length=5, null=True)),
                ('cultural_training', models.CharField(help_text='Staff cultural competency/effectiveness training?', max_length=250, null=True)),
                ('hilsc_verified', models.BooleanField(default=False, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_agencyemergencyqueue', to=settings.AUTH_USER_MODEL)),
                ('related_agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_agency_agencyemergencyqueue', to='api.Agency')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_agencyemergencyqueue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_agency_emergency_queue',
                'ordering': ['name'],
            },
        ),
    ]
