# Generated by Django 2.2.5 on 2019-11-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20191116_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyemergencyqueue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='agencyemergencyqueue',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='agencyemergencyqueue',
            name='related_agency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_agency_agencyemergencyqueue', to='api.Agency'),
        ),
        migrations.AlterField(
            model_name='agencyqueue',
            name='related_agency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_agency_agencyqueue', to='api.Agency'),
        ),
        migrations.AlterField(
            model_name='agencyqueue',
            name='requested_by_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
