# Generated by Django 2.2.5 on 2019-11-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20191117_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldPrograms',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='old_id',
        ),
    ]
