# Generated by Django 2.2.5 on 2019-11-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20191117_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='emergency_message',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
