# Generated by Django 2.2.5 on 2020-02-15 18:09

import api.models.advocacy_report
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0024_appsettings_emergency_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvocacyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('submitter_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('entity_reported', models.IntegerField(choices=[(1, api.models.advocacy_report.AdvocacyReportEntity(1)), (2, api.models.advocacy_report.AdvocacyReportEntity(2))])),
                ('entity_reported_id', models.IntegerField()),
                ('description', models.TextField()),
                ('recommendation', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AdvocacyReport',
                'verbose_name_plural': 'AdvocacyReports',
                'db_table': 'api_advocacy_reports',
            },
        ),
    ]
