# Generated by Django 2.2.5 on 2020-02-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200215_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocacyreport',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advocacyreport',
            name='status',
            field=models.CharField(default='Open', max_length=45),
        ),
    ]
