# Generated by Django 2.2.5 on 2020-02-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200215_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocacyreport',
            name='incident_date',
        ),
        migrations.RemoveField(
            model_name='advocacyreport',
            name='incident_time',
        ),
        migrations.AddField(
            model_name='advocacyreport',
            name='incident_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
