# Generated by Django 2.2.5 on 2020-02-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200216_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocacyreport',
            name='incident_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
