# Generated by Django 2.2.5 on 2020-04-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200411_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='proof_of_address',
        ),
        migrations.RemoveField(
            model_name='agencyemergencyqueue',
            name='proof_of_address',
        ),
        migrations.RemoveField(
            model_name='agencyqueue',
            name='proof_of_address',
        ),
    ]
