# Generated by Django 2.2.5 on 2020-04-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200411_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='proof_of_address_second',
            new_name='proof_of_address',
        ),
        migrations.RenameField(
            model_name='agencyemergencyqueue',
            old_name='proof_of_address_second',
            new_name='proof_of_address',
        ),
        migrations.RenameField(
            model_name='agencyqueue',
            old_name='proof_of_address_second',
            new_name='proof_of_address',
        ),
    ]
