# Generated by Django 2.2.5 on 2020-04-20 21:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20200411_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='proof_of_address',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='agencyemergencyqueue',
            name='proof_of_address',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='agencyqueue',
            name='proof_of_address',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None),
        ),
    ]
