# Generated by Django 2.2.5 on 2020-04-26 15:07

import api.models.advocacy_report
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200420_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocacyreport',
            name='custom_entity_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publicactionlog',
            name='entity_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='advocacyreport',
            name='entity_reported',
            field=models.IntegerField(choices=[(1, api.models.advocacy_report.AdvocacyReportEntity(1)), (2, api.models.advocacy_report.AdvocacyReportEntity(2)), (3, api.models.advocacy_report.AdvocacyReportEntity(3))]),
        ),
        migrations.AlterField(
            model_name='advocacyreport',
            name='entity_reported_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='gender',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agencyemergencyqueue',
            name='gender',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agencyqueue',
            name='gender',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
